name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Install dependencies
      run: pnpm install
    
    - name: Build frontend
      run: cd apps/clearwatch/web && pnpm build
    
      
    - name: Install Supabase CLI
      run: |
        curl -L https://github.com/supabase/cli/releases/download/v1.127.3/supabase_1.127.3_linux_amd64.deb -o supabase.deb
        sudo dpkg -i supabase.deb
        
    - name: Deploy Edge Functions
      if: github.ref == 'refs/heads/main'
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        PROJECT_ID: bpfdfcfgxhaogyzijrvo
      run: |
        cd apps/clearwatch/api
        supabase functions deploy --project-ref $PROJECT_ID